### ISSUE TITLE
Scraper config incomplete

### ISSUE THREAD

**Issue by gfr10598** [m-lab/scraper#45]
It looks like scraper is not scraping all active mlab machines.
For example, lga02 seems to be very active in the legacy pipeline output on May 10.  But there are no lga02 files from scraper for May 12 through May 19.

This spreadsheet shows the correspondence between test counts from the old and new pipeline.  It looks at May 10 for the old pipeline, and May 17 for the new pipeline, since we don't have fully overlapping data yet.

https://docs.google.com/spreadsheets/d/1nN7GdcSF6WnMbOM9pp1zbRBSxk1BWPTB6wRtDOKCnc4/edit#gid=389262935

**Comment by pboothe** [comment]
We think this is due to too-small disks on the GCE instances. The first fix was to move all the instances in the cluster from 40G disks to 100G disks.  

The longer term fix is to associate 110G of storage with each NDT instance and 10G of storage with each other rsync endpoint, and then scraper will have 10% more disc allocated for its scratch space than any machine in the fleet has allocated for itself.

**Comment by pboothe** [comment]
Longer term fix is in.
